### ISSUE TITLE
Webserver with a login page + background and logo

### ISSUE THREAD

**Issue by Perrypackettracer** [Perrypackettracer/Active-Domain#3]
Creating a full authentication system with a login page, username, password, and styling involves several steps. Below is a simple example using Node.js, Express, and the EJS template engine for rendering HTML. This example does not include actual user authentication but demonstrates the structure of a login page with a background and logo.

### Prerequisites:

1. Follow the steps in the previous answer to set up a basic Node.js project with Express.

2. Install the `ejs` package for rendering HTML templates:

   ```bash
   npm install ejs
   ```

### Project Structure:

```
/project
|-- node_modules
|-- views
|   |-- login.ejs
|-- public
|   |-- styles
|       |-- style.css
|-- server.js
|-- package.json
```

### Steps to Create a Login Page:

**1. Update `server.js`:**

```javascript
// server.js
const express = require('express');
const app = express();
const port = 3000;

// Set up EJS as the view engine
app.set('view engine', 'ejs');

// Serve static files from the public directory
app.use(express.static('public'));

// Define a route for the login page
app.get('/login', (req, res) => {
  res.render('login');
});

app.listen(port, () => {
  console.log(`Server is running at http://localhost:${port}`);
});
```

**2. Create the `login.ejs` Template:**

Create a new file `login.ejs` in the `views` directory.

```html
<!-- views/login.ejs -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/styles/style.css">
  <title>Login</title>
</head>
<body>
  <div class="login-container">
    <img src="/images/logo.png" alt="Logo">
    <h2>Login</h2>
    <form action="/login" method="post">
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" required>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required>
      <button type="submit">Login</button>
    </form>
  </div>
</body>
</html>
```

**3. Create Styling (CSS):**

Create a file `style.css` in the `public/styles` directory.

```css
/* public/styles/style.css */
body {
  margin: 0;
  padding: 0;
  font-family: 'Arial', sans-serif;
  background: url('/images/background.jpg') no-repeat center center fixed;
  background-size: cover;
  color: white;
}

.login-container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}

img {
  width: 100px;
  height: 100px;
  margin-bottom: 20px;
}
```

**4. Add Background and Logo:**

Place your background image (`background.jpg`) in the `public/images` directory and your logo (`logo.png`) in the same directory.

**5. Start the Server:**

Run the server using:

```bash
node server.js
```

Visit [http://localhost:3000/login](http://localhost:3000/login) to see your login page with background and logo.

Note: In a real-world scenario, you'd need to implement user authentication, sessions, and security measures. For handling user authentication, consider using a library like Passport.js.
